export const BrandsData = [
  {
    _id: 1,
    brand_name: "Canon",
    brand_image: "https://images.unsplash.com/photo-1593642532842-9",
    available_stock: 100,
  },
  {
    _id: 2,
    brand_name: "Canon",
    brand_image: "https://images.unsplash.com/photo-1593642532842-9",
    available_stock: 500,
  },
  {
    _id: 3,
    brand_name: "Canon",
    brand_image: "https://images.unsplash.com/photo-1593642532842-9",
    available_stock: 10,
  },
  {
    _id: 3,
    brand_name: "Canon",
    brand_image: "https://images.unsplash.com/photo-1593642532842-9",
    available_stock: 10,
  },
  {
    _id: 3,
    brand_name: "Canon",
    brand_image: "https://images.unsplash.com/photo-1593642532842-9",
    available_stock: 10,
  },
  {
    _id: 3,
    brand_name: "Canon",
    brand_image: "https://images.unsplash.com/photo-1593642532842-9",
    available_stock: 10,
  },
  {
    _id: 3,
    brand_name: "Canon",
    brand_image: "https://images.unsplash.com/photo-1593642532842-9",
    available_stock: 10,
  },
  {
    _id: 3,
    brand_name: "Canon",
    brand_image: "https://images.unsplash.com/photo-1593642532842-9",
    available_stock: 10,
  },
  {
    _id: 3,
    brand_name: "Canon",
    brand_image: "https://images.unsplash.com/photo-1593642532842-9",
    available_stock: 10,
  },
  {
    _id: 3,
    brand_name: "Canon",
    brand_image: "https://images.unsplash.com/photo-1593642532842-9",
    available_stock: 10,
  },
];

export const BrandsProductData = [
  {
    _id: "01",
    product_name: "HP Laser 107w Single Function Laser Printer",
    product_image: "https://images.unsplash.com/300",
    brand_name: "HP",
    product_stock: 100,
    product_price: 500,
  },
  {
    _id: "02",
    product_name: "HP Smart Tank 500 All-in-One Printer",
    product_image: "https://images.unsplash.com/300",
    brand_name: "HP",
    product_stock: 52,
    product_price: 1000,
  },
  {
    _id: "03",
    product_name:
      "Epson EcoTank L8050 Wi-Fi Single Function Color Ink Tank Printer",
    product_image: "https://images.unsplash.com/300",
    brand_name: "Epson",
    product_stock: 65,
    product_price: 1500,
  },
  {
    _id: "04",
    product_name: "Brother HL-L2320D Auto Duplex Laser Printer (30 PPM)",
    product_image: "https://images.unsplash.com/300",
    brand_name: "BROTHER",
    product_stock: 0,
    product_price: 5500,
  },
  {
    _id: "05",
    product_name: "Pantum P2506 Single Function Mono Laser Printer (22 PPM)",
    product_image: "https://images.unsplash.com/300",
    brand_name: "PANTUM",
    product_stock: 25,
    product_price: 1399,
  },
  {
    _id: "06",
    product_name:
      "Canon Pixma iP110 Portable Inkjet Wifi Printer with Battery Pack",
    product_image: "https://images.unsplash.com/300",
    brand_name: "CANON",
    product_stock: 0,
    product_price: 6500,
  },
  {
    _id: "07",
    product_name: "Canon imageCLASS LBP214dw Single Function Laser Printer",
    product_image: "https://images.unsplash.com/300",
    brand_name: "Apple",
    product_stock: 35,
    product_price: 9900,
  },
  {
    _id: "08",
    product_name: "HP Laser 107w Single Function Laser Printer",
    product_image: "https://images.unsplash.com/300",
    brand_name: "Apple",
    product_stock: 0,
    product_price: 500,
  },
  {
    _id: "09",
    product_name: "HP Laser 107w Single Function Laser Printer",
    product_image: "https://images.unsplash.com/300",
    brand_name: "Apple",
    product_stock: 0,
    product_price: 500,
  },
  {
    _id: "10",
    product_name: "HP Laser 107w Single Function Laser Printer",
    product_image: "https://images.unsplash.com/300",
    brand_name: "Apple",
    product_stock: 0,
    product_price: 500,
  },
];
