// selling statistics chart data by Nizam
export const orders = [
  {
    id: 1,
    orderId: "#1220",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cash",
    amount: 1230,
    status: "Delivered",
    // pageName: "quickOrder ",
  },
  {
    id: 3,
    orderId: "#1250",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cart",
    amount: 1230,
    status: "Cancelled",
  },
  {
    id: 4,
    orderId: "#1260",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cart",
    amount: 1230,
    status: "Delivered",
  },
  {
    id: 5,
    orderId: "#1270",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cart",
    amount: 1230,
    status: "Shipping",
  },
  {
    id: 6,
    orderId: "#1280",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cart",
    amount: 1230,
    status: "Packaging",
  },
  {
    id: 7,
    orderId: "#1290",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cart",
    amount: 1230,
    status: "Delivered",
  },
  {
    id: 8,
    orderId: "#1210",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cash",
    amount: 1230,
    status: "Order Placed",
  },
  {
    id: 9,
    orderId: "#1702",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cash",
    amount: 1230,
    status: "Delivered",
  },
];
// selling statistics chart data by Nizam
export const homeOrders = [
  {
    id: 1,
    orderId: "#1220",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cash",
    amount: 1230,
    status: "Delivered",
    page: "1",
  },
  {
    id: 3,
    orderId: "#1250",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cart",
    amount: 1230,
    status: "Cancelled",
    page: "1",
  },
  {
    id: 4,
    orderId: "#1260",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cart",
    amount: 1230,
    status: "Delivered",
    page: "1",
  },
  {
    id: 5,
    orderId: "#1270",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cart",
    amount: 1230,
    status: "Shipping",
    page: "1",
  },
  {
    id: 6,
    orderId: "#1280",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cart",
    amount: 1230,
    status: "Packaging",
    page: "1",
  },
  {
    id: 7,
    orderId: "#1290",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cart",
    amount: 1230,
    status: "Delivered",
    page: "1",
  },
  {
    id: 8,
    orderId: "#1210",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cash",
    amount: 1230,
    status: "Order Placed",
    page: "1",
  },
  {
    id: 9,
    orderId: "#1702",
    orderTime: "Des 12, 2023",
    customerName: "Ni Rimon",
    method: "Cash",
    amount: 1230,
    status: "Delivered",
    page: "1",
  },
];
// orderTableTheads
export const orderTableTheads = [
  {
    id: 1,
    sl: "Sl",
    orderId: "Order Id",
    OrderTime: "Order Time",
    customerName: "Customer",
    name: "Name",
    method: "Method",
    amount: "Amount",
    status: "Status",
    action: "Action",
    invoice: "Invoice",
  },
];
// orderTableTheads
export const homeOrderTableTheads = [
  {
    id: 1,
    orderId: "Order Id",
    OrderTime: "Order Time",
    customerName: "Customer",
    name: "Name",
    method: "Method",
    amount: "Amount",
    status: "Status",
    action: "Action",
    invoice: "View",
    page: "1",
  },
];
